#!/bin/sh
rm -rf onstream
mkdir -p onstream/onstreamsg
mkdir -p onstream/driver-22
mkdir -p onstream/driver-24
mkdir -p onstream/tools
cp -p README.onstream onstream/README
cp -p Makefile.master onstream/Makefile
for name in osst.c osst.h osst_detect.h osst_options.h Makefile Makefile.osst Makedevs.sh osst-22.diff README.osst README.osst.kernel dev-reg.txt;
 do cp -p 2.2/Driver/$name onstream/driver-22/;
done
for name in osst.c osst.h osst_detect.h osst_options.h Makefile Makefile.osst Makedevs.sh osst-24.diff README.osst README.osst.kernel dev-reg.txt;
 do cp -p 2.4/Driver/$name onstream/driver-24/;
done
cp -p Misc/onstreamsg/Makefile Misc/onstreamsg/onstreamsg.cpp onstream/onstreamsg/
cp -p Misc/onstreamsg/COPYING onstream/
cp -p Misc/tapeinfo onstream/
for name in Makefile README os_dump.c os_write.c sg_err.c sg_err.h stream.c;
 do cp -p Misc/sg_utils/$name onstream/tools/;
done
cp -pf Makefile.tools onstream/tools/Makefile
DATE=`date +"%Y%m%d"`
tar cvf onstream-${DATE}.tar onstream/
gzip -9f onstream-${DATE}.tar

